export const SERVICE_CODES = {
  ADD_ON_CREATED: "SERVICE_ADD_ON_CREATED",
  ADD_ON_CREATE_FAILED: "SERVICE_ADD_ON_CREATE_FAILED",
  ADD_ON_NOT_FOUND: "SERVICE_ADD_ON_NOT_FOUND",
  ADD_ON_UPDATED: "SERVICE_ADD_ON_UPDATED",
  ADD_ON_UPDATE_FAILED: "SERVICE_ADD_ON_UPDATE_FAILED",
  BRANCH_NOT_FOUND: "SERVICE_BRANCH_NOT_FOUND",
  CATEGORY_CREATED: "SERVICE_CATEGORY_CREATED",
  CATEGORY_CREATE_FAILED: "SERVICE_CATEGORY_CREATE_FAILED",
  CATEGORY_DUPLICATE: "SERVICE_CATEGORY_DUPLICATE",
  CATEGORY_NOT_FOUND: "SERVICE_CATEGORY_NOT_FOUND",
  CATEGORY_UPDATED: "SERVICE_CATEGORY_UPDATED",
  CATEGORY_UPDATE_FAILED: "SERVICE_CATEGORY_UPDATE_FAILED",
  CATEGORIES_LISTED: "SERVICE_CATEGORIES_LISTED",
  CATEGORIES_LOAD_FAILED: "SERVICE_CATEGORIES_LOAD_FAILED",
  FORBIDDEN: "SERVICE_FORBIDDEN",
  SERVICE_CREATED: "SERVICE_CREATED",
  SERVICE_CREATE_FAILED: "SERVICE_CREATE_FAILED",
  SERVICE_DUPLICATE: "SERVICE_DUPLICATE",
  SERVICE_LOADED: "SERVICE_LOADED",
  SERVICE_LOAD_FAILED: "SERVICE_LOAD_FAILED",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  SERVICE_UPDATED: "SERVICE_UPDATED",
  SERVICE_UPDATE_FAILED: "SERVICE_UPDATE_FAILED",
  SERVICES_LISTED: "SERVICES_LISTED",
  SERVICES_LOAD_FAILED: "SERVICES_LOAD_FAILED",
  VALIDATION_ERROR: "SERVICE_VALIDATION_ERROR",
  VARIANT_CREATED: "SERVICE_VARIANT_CREATED",
  VARIANT_CREATE_FAILED: "SERVICE_VARIANT_CREATE_FAILED",
  VARIANT_NOT_FOUND: "SERVICE_VARIANT_NOT_FOUND",
  VARIANT_UPDATED: "SERVICE_VARIANT_UPDATED",
  VARIANT_UPDATE_FAILED: "SERVICE_VARIANT_UPDATE_FAILED",
} as const;

export const SERVICE_MESSAGES = {
  ADD_ON_CREATED: "Service add-on created successfully.",
  ADD_ON_CREATE_FAILED: "Could not create service add-on. Please try again later.",
  ADD_ON_NOT_FOUND: "Service add-on was not found.",
  ADD_ON_UPDATED: "Service add-on updated successfully.",
  ADD_ON_UPDATE_FAILED: "Could not update service add-on. Please try again later.",
  BRANCH_NOT_FOUND: "Selected branch was not found.",
  CATEGORY_CREATED: "Service category created successfully.",
  CATEGORY_CREATE_FAILED: "Could not create service category. Please try again later.",
  CATEGORY_DUPLICATE: "Service category slug already exists for this scope.",
  CATEGORY_NOT_FOUND: "Service category was not found.",
  CATEGORY_UPDATED: "Service category updated successfully.",
  CATEGORY_UPDATE_FAILED: "Could not update service category. Please try again later.",
  CATEGORIES_LISTED: "Service categories loaded successfully.",
  CATEGORIES_LOAD_FAILED: "Could not load service categories. Please try again later.",
  FORBIDDEN: "You do not have permission to manage this service resource.",
  SERVICE_CREATED: "Service created successfully.",
  SERVICE_CREATE_FAILED: "Could not create service. Please try again later.",
  SERVICE_DUPLICATE: "Service slug already exists for this branch.",
  SERVICE_LOADED: "Service loaded successfully.",
  SERVICE_LOAD_FAILED: "Could not load service. Please try again later.",
  SERVICE_NOT_FOUND: "Service was not found.",
  SERVICE_UPDATED: "Service updated successfully.",
  SERVICE_UPDATE_FAILED: "Could not update service. Please try again later.",
  SERVICES_LISTED: "Services loaded successfully.",
  SERVICES_LOAD_FAILED: "Could not load services. Please try again later.",
  VALIDATION_ERROR: "Please check the service request and try again.",
  VARIANT_CREATED: "Service variant created successfully.",
  VARIANT_CREATE_FAILED: "Could not create service variant. Please try again later.",
  VARIANT_NOT_FOUND: "Service variant was not found.",
  VARIANT_UPDATED: "Service variant updated successfully.",
  VARIANT_UPDATE_FAILED: "Could not update service variant. Please try again later.",
} as const;
