export const STAFF_CODES = {
  BRANCH_NOT_FOUND: "STAFF_BRANCH_NOT_FOUND",
  FORBIDDEN: "STAFF_FORBIDDEN",
  LEAVE_CREATED: "STAFF_LEAVE_CREATED",
  LEAVE_CREATE_FAILED: "STAFF_LEAVE_CREATE_FAILED",
  LEAVE_NOT_FOUND: "STAFF_LEAVE_NOT_FOUND",
  LEAVE_UPDATED: "STAFF_LEAVE_UPDATED",
  LEAVE_UPDATE_FAILED: "STAFF_LEAVE_UPDATE_FAILED",
  SERVICE_ASSIGNED: "STAFF_SERVICE_ASSIGNED",
  SERVICE_NOT_FOUND: "STAFF_SERVICE_NOT_FOUND",
  SERVICE_REMOVED: "STAFF_SERVICE_REMOVED",
  SERVICE_UPDATE_FAILED: "STAFF_SERVICE_UPDATE_FAILED",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_CREATE_FAILED: "STAFF_CREATE_FAILED",
  STAFF_LISTED: "STAFF_LISTED",
  STAFF_LIST_LOAD_FAILED: "STAFF_LIST_LOAD_FAILED",
  STAFF_LOADED: "STAFF_LOADED",
  STAFF_LOAD_FAILED: "STAFF_LOAD_FAILED",
  STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
  STAFF_UPDATED: "STAFF_UPDATED",
  STAFF_UPDATE_FAILED: "STAFF_UPDATE_FAILED",
  USER_NOT_FOUND: "STAFF_USER_NOT_FOUND",
  VALIDATION_ERROR: "STAFF_VALIDATION_ERROR",
} as const;

export const STAFF_MESSAGES = {
  BRANCH_NOT_FOUND: "Selected branch was not found.",
  FORBIDDEN: "You do not have permission to manage this staff resource.",
  LEAVE_CREATED: "Staff leave created successfully.",
  LEAVE_CREATE_FAILED: "Could not create staff leave. Please try again later.",
  LEAVE_NOT_FOUND: "Staff leave was not found.",
  LEAVE_UPDATED: "Staff leave updated successfully.",
  LEAVE_UPDATE_FAILED: "Could not update staff leave. Please try again later.",
  SERVICE_ASSIGNED: "Staff service assigned successfully.",
  SERVICE_NOT_FOUND: "Selected service was not found.",
  SERVICE_REMOVED: "Staff service removed successfully.",
  SERVICE_UPDATE_FAILED: "Could not update staff services. Please try again later.",
  STAFF_CREATED: "Staff profile created successfully.",
  STAFF_CREATE_FAILED: "Could not create staff profile. Please try again later.",
  STAFF_LISTED: "Staff loaded successfully.",
  STAFF_LIST_LOAD_FAILED: "Could not load staff. Please try again later.",
  STAFF_LOADED: "Staff details loaded successfully.",
  STAFF_LOAD_FAILED: "Could not load staff details. Please try again later.",
  STAFF_NOT_FOUND: "Staff member was not found.",
  STAFF_UPDATED: "Staff profile updated successfully.",
  STAFF_UPDATE_FAILED: "Could not update staff profile. Please try again later.",
  USER_NOT_FOUND: "Selected user was not found.",
  VALIDATION_ERROR: "Please check the staff request and try again.",
} as const;
