export const BOOKING_CODES = {
  ADMIN_BOOKING_ACTION_FAILED: "ADMIN_BOOKING_ACTION_FAILED",
  ADMIN_BOOKING_LIST_LOAD_FAILED: "ADMIN_BOOKING_LIST_LOAD_FAILED",
  ADMIN_BOOKING_LIST_LOADED: "ADMIN_BOOKING_LIST_LOADED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_CANCEL_FAILED: "BOOKING_CANCEL_FAILED",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CREATE_FAILED: "BOOKING_CREATE_FAILED",
  BOOKING_DETAIL_LOAD_FAILED: "BOOKING_DETAIL_LOAD_FAILED",
  BOOKING_DETAIL_LOADED: "BOOKING_DETAIL_LOADED",
  BOOKING_LIST_LOAD_FAILED: "BOOKING_LIST_LOAD_FAILED",
  BOOKING_LIST_LOADED: "BOOKING_LIST_LOADED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_STATUS_UPDATED: "BOOKING_STATUS_UPDATED",
  BOOKING_RESCHEDULED: "BOOKING_RESCHEDULED",
  BOOKING_RESCHEDULE_FAILED: "BOOKING_RESCHEDULE_FAILED",
  BOOKING_SLOTS_LOAD_FAILED: "BOOKING_SLOTS_LOAD_FAILED",
  BOOKING_SLOTS_LISTED: "BOOKING_SLOTS_LISTED",
  BRANCH_NOT_FOUND: "BOOKING_BRANCH_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "BOOKING_INVALID_STATUS_TRANSITION",
  SLOT_UNAVAILABLE: "BOOKING_SLOT_UNAVAILABLE",
  SERVICE_NOT_FOUND: "BOOKING_SERVICE_NOT_FOUND",
  STAFF_NOT_FOUND: "BOOKING_STAFF_NOT_FOUND",
  VALIDATION_ERROR: "BOOKING_VALIDATION_ERROR",
  VARIANT_NOT_FOUND: "BOOKING_VARIANT_NOT_FOUND",
} as const;

export const BOOKING_MESSAGES = {
  ADMIN_BOOKING_ACTION_FAILED: "Could not update booking. Please try again later.",
  ADMIN_BOOKING_LIST_LOAD_FAILED: "Could not load admin bookings. Please try again later.",
  ADMIN_BOOKING_LIST_LOADED: "Admin bookings loaded successfully.",
  BOOKING_CANCEL_FAILED: "Could not cancel booking. Please try again later.",
  BOOKING_CANCELLED: "Booking cancelled successfully.",
  BOOKING_CREATE_FAILED: "Could not create booking. Please try again later.",
  BOOKING_CREATED: "Booking created successfully.",
  BOOKING_DETAIL_LOAD_FAILED: "Could not load booking details. Please try again later.",
  BOOKING_DETAIL_LOADED: "Booking details loaded successfully.",
  BOOKING_LIST_LOAD_FAILED: "Could not load bookings. Please try again later.",
  BOOKING_LIST_LOADED: "Bookings loaded successfully.",
  BOOKING_NOT_FOUND: "Booking was not found.",
  BOOKING_STATUS_UPDATED: "Booking status updated successfully.",
  BOOKING_RESCHEDULE_FAILED: "Could not reschedule booking. Please try again later.",
  BOOKING_RESCHEDULED: "Booking rescheduled successfully.",
  BOOKING_SLOTS_LOAD_FAILED: "Could not load booking slots. Please try again later.",
  BOOKING_SLOTS_LISTED: "Booking slots loaded successfully.",
  BRANCH_NOT_FOUND: "Selected branch was not found.",
  INVALID_STATUS_TRANSITION: "Booking cannot be changed in its current status.",
  SLOT_UNAVAILABLE: "Selected booking slot is no longer available.",
  SERVICE_NOT_FOUND: "Selected service was not found.",
  STAFF_NOT_FOUND: "Selected staff member was not found for this service.",
  VALIDATION_ERROR: "Please check the booking request and try again.",
  VARIANT_NOT_FOUND: "Selected service variant was not found.",
} as const;
