export const USER_CODES = {
  ADDRESS_CREATED: "USER_ADDRESS_CREATED",
  ADDRESS_DELETED: "USER_ADDRESS_DELETED",
  ADDRESS_LISTED: "USER_ADDRESSES_LISTED",
  ADDRESS_UPDATED: "USER_ADDRESS_UPDATED",
  ADDRESS_WRITE_FAILED: "USER_ADDRESS_WRITE_FAILED",
  ADDRESSES_LOAD_FAILED: "USER_ADDRESSES_LOAD_FAILED",
  AVATAR_REMOVED: "USER_AVATAR_REMOVED",
  AVATAR_REMOVE_FAILED: "USER_AVATAR_REMOVE_FAILED",
  AVATAR_UPDATED: "USER_AVATAR_UPDATED",
  AVATAR_UPDATE_FAILED: "USER_AVATAR_UPDATE_FAILED",
  BOOKING_HISTORY_LOADED: "USER_BOOKING_HISTORY_LOADED",
  BOOKING_HISTORY_LOAD_FAILED: "USER_BOOKING_HISTORY_LOAD_FAILED",
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  PROFILE_LOADED: "USER_PROFILE_LOADED",
  PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  PROFILE_LOAD_FAILED: "USER_PROFILE_LOAD_FAILED",
  PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",
  USER_ADDRESS_NOT_FOUND: "USER_ADDRESS_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export const USER_MESSAGES = {
  ADDRESS_CREATED: "Address saved successfully.",
  ADDRESS_DELETED: "Address deleted successfully.",
  ADDRESS_LISTED: "Addresses loaded successfully.",
  ADDRESS_UPDATED: "Address updated successfully.",
  ADDRESS_WRITE_FAILED: "Could not save address. Please try again later.",
  ADDRESSES_LOAD_FAILED: "Could not load addresses. Please try again later.",
  AVATAR_REMOVED: "Avatar removed successfully.",
  AVATAR_REMOVE_FAILED: "Could not remove avatar. Please try again later.",
  AVATAR_UPDATED: "Avatar updated successfully.",
  AVATAR_UPDATE_FAILED: "Could not update avatar. Please try again later.",
  BOOKING_HISTORY_LOADED: "Booking history loaded successfully.",
  BOOKING_HISTORY_LOAD_FAILED: "Could not load booking history. Please try again later.",
  BRANCH_NOT_FOUND: "Selected branch was not found.",
  INVALID_ADDRESS_PAYLOAD: "Please provide at least one address field.",
  INVALID_AVATAR_URL: "Please provide a valid avatar URL.",
  INVALID_EMAIL: "Please enter a valid email address.",
  INVALID_NAME: "Name must be between 2 and 100 characters.",
  INVALID_PROFILE_PAYLOAD: "Please provide at least one profile field.",
  INVALID_REQUEST_BODY: "Request body is invalid.",
  PROFILE_LOADED: "Profile loaded successfully.",
  PROFILE_LOAD_FAILED: "Could not load profile. Please try again later.",
  PROFILE_UPDATED: "Profile updated successfully.",
  PROFILE_UPDATE_FAILED: "Could not update profile. Please try again later.",
  USER_ADDRESS_NOT_FOUND: "Address was not found.",
} as const;
