import "server-only";

import { deleteFromCloudinary } from "@/lib/cloudinary";
import {
  MediaAccessDeniedError,
  MediaAlreadyExistsError,
  MediaNotFoundError,
} from "./media.errors";
import {
  createMediaAsset,
  findMediaAssetById,
  listMediaAssets,
  softDeleteMediaAsset,
} from "./media.repository";
import type {
  CreateMediaAssetInput,
  ListMediaQuery,
  PaginatedMedia,
  PublicMediaAsset,
} from "./media.types";

/**
 * Persists a Cloudinary asset after the browser finished uploading it.
 *
 * The public ID is generated by the signed-upload action. Checking its exact
 * user prefix prevents callers from registering another user's asset.
 */
export async function saveMediaAsset(
  userId: string,
  input: CreateMediaAssetInput,
): Promise<PublicMediaAsset> {
  const folder = `nikharta-roop/${userId}`;
  if (
    input.purpose === "VERIFICATION" ||
    input.attachedToType === "SALON_VERIFICATION"
  )
    throw new MediaAccessDeniedError();
  if (!input.publicId.startsWith(`${folder}/`)) {
    throw new MediaAccessDeniedError();
  }

  try {
    return await createMediaAsset(userId, { ...input, folder });
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "P2002"
    ) {
      throw new MediaAlreadyExistsError();
    }
    throw error;
  }
}

/** Paginated library for the current user. */
export async function listUserMedia(
  userId: string,
  query: ListMediaQuery,
): Promise<PaginatedMedia> {
  return listMediaAssets(userId, query);
}

/**
 * Deletes an asset the caller owns.
 *
 * Cloudinary deletion is best-effort so a temporary provider failure does
 * not keep the item visible in the user's library. The soft-deleted row
 * retains the public ID for later reconciliation.
 */
export async function deleteMediaAsset(
  userId: string,
  assetId: string,
): Promise<void> {
  const asset = await findMediaAssetById(assetId);
  if (!asset) throw new MediaNotFoundError();
  if (asset.userId !== userId) throw new MediaAccessDeniedError();
  if (asset.purpose === "VERIFICATION") throw new MediaAccessDeniedError();

  await softDeleteMediaAsset(assetId);

  try {
    await deleteFromCloudinary(asset.publicId);
  } catch (error) {
    console.error("Cloudinary delete failed", asset.publicId, error);
  }
}
