export const PACKAGE_CODES = {
  BRANCH_NOT_FOUND: "PACKAGE_BRANCH_NOT_FOUND",
  CATEGORY_NOT_FOUND: "PACKAGE_CATEGORY_NOT_FOUND",
  FORBIDDEN: "PACKAGE_FORBIDDEN",
  PACKAGE_CREATED: "PACKAGE_CREATED",
  PACKAGE_CREATE_FAILED: "PACKAGE_CREATE_FAILED",
  PACKAGE_DUPLICATE: "PACKAGE_DUPLICATE",
  PACKAGE_LOADED: "PACKAGE_LOADED",
  PACKAGE_LOAD_FAILED: "PACKAGE_LOAD_FAILED",
  PACKAGE_NOT_FOUND: "PACKAGE_NOT_FOUND",
  PACKAGE_SERVICE_ASSIGNED: "PACKAGE_SERVICE_ASSIGNED",
  PACKAGE_SERVICE_ASSIGN_FAILED: "PACKAGE_SERVICE_ASSIGN_FAILED",
  PACKAGE_SERVICE_REMOVED: "PACKAGE_SERVICE_REMOVED",
  PACKAGE_SERVICE_REMOVE_FAILED: "PACKAGE_SERVICE_REMOVE_FAILED",
  PACKAGE_UPDATED: "PACKAGE_UPDATED",
  PACKAGE_UPDATE_FAILED: "PACKAGE_UPDATE_FAILED",
  PACKAGES_LISTED: "PACKAGES_LISTED",
  PACKAGES_LOAD_FAILED: "PACKAGES_LOAD_FAILED",
  SERVICE_NOT_FOUND: "PACKAGE_SERVICE_NOT_FOUND",
  VALIDATION_ERROR: "PACKAGE_VALIDATION_ERROR",
} as const;

export const PACKAGE_MESSAGES = {
  BRANCH_NOT_FOUND: "Selected branch was not found.",
  CATEGORY_NOT_FOUND: "Selected package category was not found.",
  FORBIDDEN: "You do not have permission to manage this package.",
  PACKAGE_CREATED: "Package created successfully.",
  PACKAGE_CREATE_FAILED: "Could not create package. Please try again later.",
  PACKAGE_DUPLICATE: "Package slug already exists for this branch.",
  PACKAGE_LOADED: "Package loaded successfully.",
  PACKAGE_LOAD_FAILED: "Could not load package. Please try again later.",
  PACKAGE_NOT_FOUND: "Package was not found.",
  PACKAGE_SERVICE_ASSIGNED: "Package service assigned successfully.",
  PACKAGE_SERVICE_ASSIGN_FAILED: "Could not assign package service.",
  PACKAGE_SERVICE_REMOVED: "Package service removed successfully.",
  PACKAGE_SERVICE_REMOVE_FAILED: "Could not remove package service.",
  PACKAGE_UPDATED: "Package updated successfully.",
  PACKAGE_UPDATE_FAILED: "Could not update package. Please try again later.",
  PACKAGES_LISTED: "Packages loaded successfully.",
  PACKAGES_LOAD_FAILED: "Could not load packages. Please try again later.",
  SERVICE_NOT_FOUND: "Selected service was not found for this package branch.",
  VALIDATION_ERROR: "Please check the package request and try again.",
} as const;
